name: cloutgrid_flutter
description: "Connect • Create • Collaborate"
publish_to: 'none'

version: 1.3.0+21

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  go_router: ^17.1.0
  loading_animation_widget:
  dio: ^5.7.0
  flutter_secure_storage: ^10.3.1
  riverpod_annotation: ^4.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  cached_network_image: ^3.4.1
  gradient_blur: ^1.0.2+1
  flutter_svg: ^2.3.0
  url_launcher: ^6.3.2
  crop_your_image: ^2.0.0
  image_picker: ^1.2.3
  flutter_staggered_grid_view: ^0.7.0
  crop_image: ^1.0.16
  image_size_getter: ^2.3.0
  flutter_native_splash: ^2.4.8
  web_socket_channel: ^3.0.3
  app_links: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  go_router_builder: ^4.0.1
  riverpod_generator: ^4.0.4
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cloutgrid_logo_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/cloutgrid_logo_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/cloutgrid_logo.png
    - assets/images/cloutgrid_logo_splash.png
    - assets/images/cloutgrid_logo_icon.png
    - assets/images/box.png
    - assets/images/photo.png
    - assets/images/office.png
    - assets/images/speaker.png
    - assets/images/chat.png
    - assets/images/complaint.png
    - assets/images/deal.png
    - assets/images/delete.png
    - assets/images/instagram_insight.png
    - assets/images/youtube_analytics.png
    - assets/images/delete.png
    - assets/images/kid.png
    - assets/images/profile.png
    - assets/images/image_error.jpg

    - assets/icons/instagram.svg
    - assets/icons/youtube.svg

flutter_native_splash:
  color: "#F2F0EF"
  image: assets/images/cloutgrid_logo_splash.png
  fullscreen: true

  android_12:
    color: "#F2F0EF"
    image: assets/images/cloutgrid_logo_splash.png
    icon_background_color: "#F2F0EF"
